@startuml
actor Client
participant "Controller" as C
participant "ListaServiceImpl" as S
participant "Repository" as R
participant "TarefaEntity" as Ent

Client -> C: DELETE /api/tarefas/{id}
activate C
C -> S: deletarListaTarefas(id)
activate S
S -> R: findById(id)
activate R
R --> S: Optional<TarefaEntity>
deactivate R

alt Tarefa Encontrada
    S -> R: delete(tarefa)
    activate R
    R --> S: 
    deactivate R
else Tarefa Não Encontrada
    S -> Ent: new TarefaEntity()
    S -> R: delete(tarefa)
    activate R
    R --> S: 
    deactivate R
end
deactivate S

C -> Client: ResponseEntity.ok("Tarefa deletada com sucesso")
deactivate C
@enduml
